#!/usr/bin/env bash
# Compare the committed CLI surface (.surface) against the previous release's.
#
# Usage: scripts/check-surface-compat.sh [PREV_TAG]
#
# .surface is regenerated by TestSurfaceSnapshot (`make update-surface`) and
# committed, so the baseline is simply `git show <tag>:.surface` — no second
# checkout, no second build. PREV_TAG defaults to the newest stable tag
# reachable from HEAD^ (so a release tag at HEAD compares against the one
# before it). Removals fail unless listed in .surface-breaking.
#
# Exit codes:
#   0 — no unacknowledged removals, or no baseline to compare against
#   1 — removals found, the current .surface is missing, or an explicit
#       PREV_TAG does not resolve
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CURRENT=".surface"
ALLOWLIST=".surface-breaking"

[ -f "$CURRENT" ] || { echo "FAIL: $CURRENT not found — run 'make update-surface'" >&2; exit 1; }

PREV_TAG="${1:-}"
if [ -z "$PREV_TAG" ]; then
  PREV_TAG=$(git tag --merged HEAD^ --sort=-version:refname --list 'v[0-9]*.[0-9]*.[0-9]*' 2>/dev/null \
    | awk '!/-/ { print; exit }' || true)
fi

if [ -z "$PREV_TAG" ]; then
  echo "No previous stable tag — skipping surface compatibility check"
  exit 0
fi

# A tag that does not resolve is a caller error (misspelled PREV_TAG, or an
# unfetched shallow clone), not a baseline that predates .surface — skipping
# here would silently disable the whole gate.
git rev-parse --quiet --verify "${PREV_TAG}^{commit}" >/dev/null \
  || { echo "FAIL: baseline tag ${PREV_TAG} does not resolve" >&2; exit 1; }

if ! git cat-file -e "${PREV_TAG}:${CURRENT}" 2>/dev/null; then
  echo "Baseline ${PREV_TAG} has no ${CURRENT} — skipping surface compatibility check"
  exit 0
fi

BASELINE="$(mktemp)"
trap 'rm -f "$BASELINE"' EXIT
git show "${PREV_TAG}:${CURRENT}" > "$BASELINE"

echo "Comparing ${CURRENT} against ${PREV_TAG}"
scripts/check-cli-surface-diff.sh "$BASELINE" "$CURRENT" "$ALLOWLIST"
